@baseUrl = http://localhost:3000/api/refugio
### GET ALL
GET {{baseUrl}}

### POST
POST {{baseUrl}}
Content-Type:application/json

{
  "nombre": "Guarderia pepito",
  "direccion": "Alvear 50",
  "telefono": "2131445456",
  "email": "lala@gmail.com",
  "localidad": 7
}

### GET ONE
GET {{baseUrl}}/1

### PUT
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "nombre": "Guarderia Porotos",
  "localidad": 8
}

### REMOVE
DELETE {{baseUrl}}/1